services:
  backend:
    build:
      dockerfile: Dockerfile
    image: service:1
    container_name: service
    working_dir: /app
    ports:
      - "8080:8080"
    networks:
      - service_net
    restart: unless-stopped
    command: ["python", "server.py"]

networks:
  service_net:
    name: service_net